apiVersion: v1
kind: pod
metadata:
  name: nginx
  labels:
    app: nginx
    version: v1
spec:
  containers:
    name: http-service
    image: httpd
    ports:
      containerPort: 80
    name: nginx-service
    image: nginx
    ports:
      containerPort: 80
      
    
